---
- name: create golang dir
  file:
    path: "{{ home }}/go"
    state: directory
    mode: 0755

- name: golang source directory from mega
  file:
    src: "{{ home }}/mega/go/src"
    dest: "{{ home }}/go/src"
    state: link
