#!/bin/bash

# Dependencies:

# 1. compgen #
#
# compgen is bash builtin. See `man bash`


# 2. fzf #
#
# ~ » pacman -Fs fzf
# community/fzf 0.18.0-1
#     usr/bin/fzf


# 3. lnch #
#
# lnch is from https://github.com/oem/lnch. `go get github.com/oem/lnch`
#
# This is the source code of the only file main.go:
# ```
#package main
#import (
#    "fmt"
#    "log"
#    "os"
#    "os/exec"
#    "syscall"
#)
#func main() {
#    if len(os.Args) <= 1 {
#        fmt.Println("Usage: lnch <command> <optional parameters>")
#        os.Exit(1)
#    }
#    cmd := exec.Command(os.Args[1], os.Args[2:]...)
#    // this is the important part to avoid killing the child process instantly
#    cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
#    err := cmd.Start()
#    if err != nil {
#        log.Fatal(err)
#    }
#}
# ```


set -m
compgen -c | sort -u | /usr/bin/fzf | sh
set +m
#compgen -c | sort -u | /usr/bin/fzf | xargs /home/phil/go/bin/lnch

